[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 200

remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]
